registry:
  image: registry:2
  ports:
   - "5000:5000"
  environment:
     REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
     REGISTRY_HTTP_TLS_KEY: /certs/domain.key
  volumes_from:
    - ./data:/var/lib/registry
    - ./certs:/certs
  restart: always
httpserver:
  build: dockerfiles/lab-httpd-server/
  ports:
    - "8082:80"
  restart: always
nexus:
  image: sonatype/nexus:oss
  ports:
    - "8081:8081"
  volumes_from:
    - data-volume
  restart: always
postgresqlgitlab:
  image: quay.io/sameersbn/postgresql:9.4-5
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes_from:
    - data-volume
  restart: always
redisgitlab:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
  restart: always
gitlab:
  image: quay.io/sameersbn/gitlab:8.0.5
  links:
    - redisgitlab:redisio
    - postgresqlgitlab:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_ROOT_PASSWORD=dockeradmin
    - GITLAB_USERNAME_CHANGE=false
    - GITLAB_CREATE_GROUP=false
    - GITLAB_PROJECTS_ISSUES=false
    - GITLAB_PROJECTS_MERGE_REQUESTS=false
    - GITLAB_PROJECTS_WIKI=false
    - GITLAB_BACKUPS=disable
    - GITLAB_SECRETS_DB_KEY_BASE=HQLS2pfZGZBtHlmKJrJw7Tm5QRkCQ3rKlbQBqpJWVXmkRbMRsdGMRNcrDz87zTTf
  volumes_from:
    - data-volume
  restart: always
